// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/kms/v1/kms.proto

package kmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TlsCert       string                 `protobuf:"bytes,2,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kms_v1_kms_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterClientRequest) GetTlsCert() string {
	if x != nil {
		return x.TlsCert
	}
	return ""
}

type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kms_v1_kms_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClientResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterClientResponse) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kms_v1_kms_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetSecretRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kms_v1_kms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kms_v1_kms_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_api_proto_kms_v1_kms_proto protoreflect.FileDescriptor

const file_api_proto_kms_v1_kms_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/kms/v1/kms.proto\x12\x06kms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x15RegisterClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\btls_cert\x18\x02 \x01(\tR\atlsCert\"l\n" +
	"\x16RegisterClientResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x125\n" +
	"\bvalid_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\"L\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"-\n" +
	"\x11GetSecretResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload2\x9f\x01\n" +
	"\n" +
	"KMSService\x12O\n" +
	"\x0eRegisterClient\x12\x1d.kms.v1.RegisterClientRequest\x1a\x1e.kms.v1.RegisterClientResponse\x12@\n" +
	"\tGetSecret\x12\x18.kms.v1.GetSecretRequest\x1a\x19.kms.v1.GetSecretResponseBHZFgithub.com/RomanGolovinn/KeyManagementSystem/internal/api/kms/v1;kmsv1b\x06proto3"

var (
	file_api_proto_kms_v1_kms_proto_rawDescOnce sync.Once
	file_api_proto_kms_v1_kms_proto_rawDescData []byte
)

func file_api_proto_kms_v1_kms_proto_rawDescGZIP() []byte {
	file_api_proto_kms_v1_kms_proto_rawDescOnce.Do(func() {
		file_api_proto_kms_v1_kms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kms_v1_kms_proto_rawDesc), len(file_api_proto_kms_v1_kms_proto_rawDesc)))
	})
	return file_api_proto_kms_v1_kms_proto_rawDescData
}

var file_api_proto_kms_v1_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_kms_v1_kms_proto_goTypes = []any{
	(*RegisterClientRequest)(nil),  // 0: kms.v1.RegisterClientRequest
	(*RegisterClientResponse)(nil), // 1: kms.v1.RegisterClientResponse
	(*GetSecretRequest)(nil),       // 2: kms.v1.GetSecretRequest
	(*GetSecretResponse)(nil),      // 3: kms.v1.GetSecretResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_api_proto_kms_v1_kms_proto_depIdxs = []int32{
	4, // 0: kms.v1.RegisterClientResponse.valid_to:type_name -> google.protobuf.Timestamp
	0, // 1: kms.v1.KMSService.RegisterClient:input_type -> kms.v1.RegisterClientRequest
	2, // 2: kms.v1.KMSService.GetSecret:input_type -> kms.v1.GetSecretRequest
	1, // 3: kms.v1.KMSService.RegisterClient:output_type -> kms.v1.RegisterClientResponse
	3, // 4: kms.v1.KMSService.GetSecret:output_type -> kms.v1.GetSecretResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_kms_v1_kms_proto_init() }
func file_api_proto_kms_v1_kms_proto_init() {
	if File_api_proto_kms_v1_kms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kms_v1_kms_proto_rawDesc), len(file_api_proto_kms_v1_kms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kms_v1_kms_proto_goTypes,
		DependencyIndexes: file_api_proto_kms_v1_kms_proto_depIdxs,
		MessageInfos:      file_api_proto_kms_v1_kms_proto_msgTypes,
	}.Build()
	File_api_proto_kms_v1_kms_proto = out.File
	file_api_proto_kms_v1_kms_proto_goTypes = nil
	file_api_proto_kms_v1_kms_proto_depIdxs = nil
}
